### ISSUE TITLE
An error when looking for 200 proteins in a genome

### ISSUE THREAD

**Issue by gilloe** [lh3/miniprot#46] opened 2023-06-06 10:33 UTC
Hi,
I get the following error when running miniprot looking for 200 proteins at a 73MB genome:
[M::mp_ntseq_read@0.375*1.01] read 68163509 bases in 69053 contigs
[M::mp_idx_build@0.379*1.01] 608218 blocks
[M::mp_idx_build@0.987*2.83] collected syncmers
[M::mp_idx_build@13.918*1.13] 23643989 kmer-block pairs
[M::mp_idx_print_stat] 1694743 distinct k-mers; mean occ of infrequent k-mers: 13.95; 0 frequent k-mers accounting for 0 occurrences
##gff-version 3
BUG! 1929 == 1929? 621 == 622? 40M1I57M3D83M2D98M3I8M1I59M1D26M15U117M1D46M2D30M5I27M1I5M63U12M
miniprot_: align.c:195: mp_extra_cal: Assertion `al == r->qe - r->qs' failed.
Aborted

I tried to run it looking for 20 proteins in the same genome and it worked fine, and also looked for the 200 proteins in a smaller genome, and it works fine. So I don't think it is a file format issue. 
Any suggestions?

Thanks,
Gil

**Comment by lh3** [comment] 2023-06-06 13:36
Could you share me with the proteins and the reference genome?

**Comment by gilloe** [comment] 2023-06-07 08:20
Yes, thanks.
The genome can be downloaded from: https://www.ncbi.nlm.nih.gov/nuccore/LDNA00000000.1
And the query file is attached.
[Hydra_uniprot (2).zip](https://github.com/lh3/miniprot/files/11674376/Hydra_uniprot.2.zip)

**Comment by lh3** [comment] 2023-06-08 02:37
I downloaded [the genome](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/455/295/GCA_001455295.2_ASM145529v2/) and could get the results:
```
[M::mp_ntseq_read@0.385*1.00] read 68163509 bases in 69053 contigs
[M::mp_idx_build@0.386*1.00] 608218 blocks
[M::mp_idx_build@0.794*2.52] collected syncmers
[M::mp_idx_build@1.099*2.09] 23643989 kmer-block pairs
[M::mp_idx_print_stat] 1694743 distinct k-mers; mean occ of infrequent k-mers: 13.95; 0 frequent k-mers accounting for 0 occurrences
[M::worker_pipeline::1.299*2.27] mapped 200 sequences
[M::main] Version: 0.11-r234
[M::main] CMD: ./miniprot GCA_001455295.2_ASM145529v2_genomic.fna.gz Hydra_uniprot.fasta
```
Based on the total number of bases, we are using the same reference.

What version are you using?

**Comment by gilloe** [comment] 2023-06-08 14:39
How do I know which version I have?

**Comment by lh3** [comment] 2023-06-08 15:42
`miniprot --version`. You may just try the latest version.

**Comment by gilloe** [comment] 2023-06-08 15:52
0.11-r235-dirty
I downloaded it very recently.

**Comment by lh3** [comment] 2024-09-30 19:42
Closing. Not sure what was happening, but if I couldn't reproduce the error, I wouldn't be able to fix.

**Closed by lh3** 2024-09-30 19:42 UTC
